
backend:
  name: git-gateway
  branch: main
  media_folder: static/img

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'content/guide'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown'}